// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopping.ProductAPI.Model.Context;

#nullable disable

namespace Shopping.ProductAPI.Migrations
{
    [DbContext(typeof(SQLContext))]
    [Migration("20240630124524_SeedCamisas")]
    partial class SeedCamisas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "Camisa algodão",
                            Description = "Camisa Marte Preta",
                            ImageURL = "https://github.com/DiogoLuizBonaparte/shopping/blob/master/ShoppingImages/11_mars.jpg",
                            Name = "Camisa Marte",
                            Price = 79.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Camisa",
                            Description = "Camisa Dragonball Z, Goku",
                            ImageURL = "https://github.com/DiogoLuizBonaparte/shopping/blob/master/ShoppingImages/13_dragon_ball.jpg",
                            Name = "Camisa Dragon Ball Z",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Camisa",
                            Description = "Camisa No Internet preta",
                            ImageURL = "https://github.com/DiogoLuizBonaparte/shopping/blob/master/ShoppingImages/2_no_internet.jpg",
                            Name = "Camisa No Internet",
                            Price = 19m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
